**PREPROCESSING DATA**

In [8]:
import os
from PIL import Image
import numpy as np

# Path to the folder containing the images
folder_path = './img'

# Preprocessing Function (Resize, Convert to RGB, Normalize)
def preprocess_image(img, size=(300, 300)):
    # Resize the image
    img_resized = img.resize(size)
    
    # Convert RGBA to RGB if necessary
    img_rgb = img_resized.convert('RGB')
    
    # Normalize pixel values to [0, 1]
    img_array_rgb = np.array(img_rgb) / 255.0
    
    return img_array_rgb

# List to store processed images
processed_images = []

# Loop through all files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.png') or file_name.endswith('.jpg') or file_name.endswith('.jpeg'):  # Add other image formats if needed
        image_path = os.path.join(folder_path, file_name)
        
        # Open and preprocess the image
        img = Image.open(image_path)
        processed_img = preprocess_image(img)
        processed_images.append(processed_img)

# Output the shape of each processed image
for i, img in enumerate(processed_images):
    print(f"Processed Image {i+1} Shape:", img.shape)

# Display a small portion of the array to check correctness
for i, img in enumerate(processed_images):
    print(f"Sample from Image {i+1} Array:", img[0:2, 0:2, :])

Processed Image 1 Shape: (300, 300, 3)
Processed Image 2 Shape: (300, 300, 3)
Processed Image 3 Shape: (300, 300, 3)
Processed Image 4 Shape: (300, 300, 3)
Processed Image 5 Shape: (300, 300, 3)
Processed Image 6 Shape: (300, 300, 3)
Processed Image 7 Shape: (300, 300, 3)
Sample from Image 1 Array: [[[0.81568627 0.80392157 0.74509804]
  [0.81960784 0.80392157 0.75686275]]

 [[0.83137255 0.80784314 0.76078431]
  [0.83137255 0.80784314 0.76470588]]]
Sample from Image 2 Array: [[[0.10588235 0.16078431 0.16470588]
  [0.10588235 0.16078431 0.16470588]]

 [[0.09411765 0.14901961 0.15294118]
  [0.09803922 0.15294118 0.15686275]]]
Sample from Image 3 Array: [[[0.10588235 0.2        0.16470588]
  [0.07843137 0.18039216 0.13333333]]

 [[0.05490196 0.14117647 0.10196078]
  [0.04313725 0.14117647 0.08627451]]]
Sample from Image 4 Array: [[[0.09803922 0.18039216 0.15294118]
  [0.18823529 0.27843137 0.23921569]]

 [[0.0627451  0.14509804 0.11764706]
  [0.13333333 0.21960784 0.18431373]]]
Sample from

**EKSTRAKSI FITUR**

In [9]:
# Feature extraction functions
def extract_color_features(img_array):
    # Calculate mean color for each channel (R, G, B)
    mean_colors = np.mean(img_array, axis=(0, 1))  # Mean across width and height
    return mean_colors

def extract_texture_features(img_array):
    # Calculate variance of pixel intensities to capture texture information
    variance = np.var(img_array, axis=(0, 1))  # Variance across width and height
    return variance

def extract_spatial_features(img_array, grid_size=(5, 5)):
    # Split the image into a grid and calculate mean for each grid cell
    h, w, c = img_array.shape
    grid_h, grid_w = grid_size
    spatial_features = []
    
    # Calculate the height and width of each grid cell
    cell_h, cell_w = h // grid_h, w // grid_w
    
    # Loop through grid cells and calculate mean pixel values
    for i in range(grid_h):
        for j in range(grid_w):
            cell = img_array[i*cell_h:(i+1)*cell_h, j*cell_w:(j+1)*cell_w, :]
            spatial_features.append(np.mean(cell, axis=(0, 1)))  # Mean of R, G, B values for each cell
    
    # Flatten the list of spatial features into a 1D array
    return np.array(spatial_features).flatten()

# Lists to store features
color_features_list = []
texture_features_list = []
spatial_features_list = []

# Extract features for each processed image
for img in processed_images:
    color_features = extract_color_features(img)
    texture_features = extract_texture_features(img)
    spatial_features = extract_spatial_features(img)
    
    # Store features
    color_features_list.append(color_features)
    texture_features_list.append(texture_features)
    spatial_features_list.append(spatial_features)

# Output features for each processed image
for i in range(len(processed_images)):
    print(f"Color Features for Image {i+1}:", color_features_list[i])
    print(f"Texture Features for Image {i+1}:", texture_features_list[i])
    print(f"Spatial Features for Image {i+1}:", spatial_features_list[i])

# Display a small portion of the array to check correctness for the first image
for i, img in enumerate(processed_images):
    print(f"Sample from Image {i+1} Array:", img[0:2, 0:2, :])


Color Features for Image 1: [0.34952484 0.35372501 0.34462218]
Texture Features for Image 1: [0.05128592 0.04239338 0.03950889]
Spatial Features for Image 1: [0.40148039 0.34383769 0.3345915  0.44895969 0.4138268  0.40762309
 0.39752614 0.41036492 0.40386166 0.37200654 0.39931808 0.3855207
 0.16336819 0.28125708 0.23502941 0.36883333 0.30242702 0.29435512
 0.39105011 0.35951634 0.35228214 0.24757081 0.26725817 0.28828867
 0.42060675 0.41503595 0.41303922 0.15619499 0.27687473 0.23123203
 0.46258606 0.41322113 0.40201416 0.40242593 0.39317974 0.3780207
 0.29951743 0.31510893 0.31860458 0.42216993 0.43266667 0.41485403
 0.29568845 0.34346296 0.31792484 0.49814161 0.46442157 0.46112963
 0.36871569 0.37825163 0.3690915  0.31851089 0.33076253 0.32999455
 0.34432571 0.35428867 0.35595534 0.41560566 0.40486601 0.39381373
 0.3679183  0.30865142 0.3099902  0.34876688 0.32434641 0.32059913
 0.24393573 0.31516885 0.27892702 0.26608279 0.27995969 0.29170153
 0.3161329  0.31505229 0.32711002]
Color