**PREPROCESSING DATA**

In [1]:
import os
from PIL import Image
import numpy as np

# Path to the folder containing the images
folder_path = 'D:/Semester 5/DataMining/'

# Preprocessing Function (Resize, Convert to RGB, Normalize)
def preprocess_image(img, size=(300, 300)):
    # Resize the image
    img_resized = img.resize(size)
    
    # Convert RGBA to RGB if necessary
    img_rgb = img_resized.convert('RGB')
    
    # Normalize pixel values to [0, 1]
    img_array_rgb = np.array(img_rgb) / 255.0
    
    return img_array_rgb

# List to store processed images
processed_images = []

# Loop through all files in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.png') or file_name.endswith('.jpg') or file_name.endswith('.jpeg'):  # Add other image formats if needed
        image_path = os.path.join(folder_path, file_name)
        
        # Open and preprocess the image
        img = Image.open(image_path)
        processed_img = preprocess_image(img)
        processed_images.append(processed_img)

# Output the shape of each processed image
for i, img in enumerate(processed_images):
    print(f"Processed Image {i+1} Shape:", img.shape)

# Display a small portion of the array to check correctness
for i, img in enumerate(processed_images):
    print(f"Sample from Image {i+1} Array:", img[0:2, 0:2, :])

# Continue with further steps like feature extraction or clustering

Processed Image 1 Shape: (300, 300, 3)
Processed Image 2 Shape: (300, 300, 3)
Processed Image 3 Shape: (300, 300, 3)
Processed Image 4 Shape: (300, 300, 3)
Processed Image 5 Shape: (300, 300, 3)
Processed Image 6 Shape: (300, 300, 3)
Processed Image 7 Shape: (300, 300, 3)
Sample from Image 1 Array: [[[0.16470588 0.09803922 0.1254902 ]
  [0.31764706 0.24705882 0.2745098 ]]

 [[0.2        0.1372549  0.16078431]
  [0.25490196 0.18431373 0.21176471]]]
Sample from Image 2 Array: [[[0.22352941 0.29019608 0.3254902 ]
  [0.24313725 0.30196078 0.34509804]]

 [[0.19607843 0.27058824 0.30196078]
  [0.23529412 0.30196078 0.34509804]]]
Sample from Image 3 Array: [[[0.10588235 0.16078431 0.16470588]
  [0.10588235 0.16078431 0.16470588]]

 [[0.09411765 0.14901961 0.15294118]
  [0.09803922 0.15294118 0.15686275]]]
Sample from Image 4 Array: [[[0.09803922 0.18039216 0.15294118]
  [0.18823529 0.27843137 0.23921569]]

 [[0.0627451  0.14509804 0.11764706]
  [0.13333333 0.21960784 0.18431373]]]
Sample from